# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
#orbs:
  # Declare a dependency on the welcome-orb
#  welcome: circleci/welcome-orb@0.4.1
# Orchestrate or schedule a set of jobs
#workflows:
  # Name the workflow "welcome"
 # welcome:
    # Run the welcome/run job in its own container
jobs:

  build:
    working_directory: ~/hello-sts
    docker:
      - image: circleci/node:8.11.1
    steps:
      - checkout

  deploy:
    machine:
      enabled: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - "0d:f3:cf:da:11:33:00:29:58:c0:7e:4c:f8:bd:74:9d"
      - run:
          name: Deploy over SSH
          command: ssh -p 22 centos@3.15.28.221 -v 'cd /home/circle/poc && sudo git pull' 
#          |
#                   pwd
#                   hostname
#                   ssh -p 22 centos@3.15.28.221 -v
#                   pwd
#                   cd /home/circle/poc
#                   pwd
#                   hostname
#                   sudo git pull
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build